// ============================================================
// Body chart — surface landmark catalog (skin-mode point features)
// ============================================================
//
// GENERATED by scripts/gen-body-surface.mjs — do not edit by hand.
// Face features from the head bbox, torso points from the neck / groin anchors,
// arm joints interpolated from biceps/forearm/hand centres, every point snapped
// inside the silhouette. Leader-only anchors (no fill); a `left`/`right`
// modifier selects a bilateral landmark's side via `centers`.

import type { BodyPartGeometry, FigureKey } from '../types';

type SurfaceGeom = Omit<BodyPartGeometry, 'paths'>;

export const SURFACE: Readonly<Record<FigureKey, Record<string, SurfaceGeom>>> =
  {
    maleFront: {
      forehead: { anchor: { x: 364, y: 168 }, centers: [{ x: 364, y: 168 }] },
      eye: {
        anchor: { x: 364, y: 179 },
        centers: [
          { x: 339, y: 179 },
          { x: 389, y: 179 },
        ],
      },
      nose: { anchor: { x: 364, y: 197 }, centers: [{ x: 364, y: 197 }] },
      cheek: {
        anchor: { x: 364, y: 207 },
        centers: [
          { x: 329, y: 207 },
          { x: 399, y: 207 },
        ],
      },
      ear: {
        anchor: { x: 364, y: 186 },
        centers: [
          { x: 304, y: 186 },
          { x: 424, y: 186 },
        ],
      },
      mouth: { anchor: { x: 364, y: 222 }, centers: [{ x: 364, y: 222 }] },
      jaw: {
        anchor: { x: 364, y: 235 },
        centers: [
          { x: 326, y: 236 },
          { x: 402, y: 234 },
        ],
      },
      chin: { anchor: { x: 364, y: 249 }, centers: [{ x: 364, y: 249 }] },
      throat: { anchor: { x: 364, y: 287 }, centers: [{ x: 364, y: 287 }] },
      collarbone: {
        anchor: { x: 364, y: 301 },
        centers: [
          { x: 294, y: 301 },
          { x: 434, y: 301 },
        ],
      },
      sternum: { anchor: { x: 364, y: 413 }, centers: [{ x: 364, y: 413 }] },
      belly: { anchor: { x: 364, y: 549 }, centers: [{ x: 364, y: 549 }] },
      navel: { anchor: { x: 364, y: 597 }, centers: [{ x: 364, y: 597 }] },
      hip: {
        anchor: { x: 364, y: 660 },
        centers: [
          { x: 329, y: 660 },
          { x: 399, y: 660 },
        ],
      },
      groin: { anchor: { x: 370, y: 772 }, centers: [{ x: 370, y: 772 }] },
      elbow: {
        anchor: { x: 344, y: 463 },
        centers: [
          { x: 197, y: 462 },
          { x: 491, y: 464 },
        ],
      },
      wrist: {
        anchor: { x: 170, y: 712 },
        centers: [
          { x: 96, y: 696 },
          { x: 244, y: 728 },
        ],
      },
    },
    maleBack: {
      ear: {
        anchor: { x: 1083, y: 166 },
        centers: [
          { x: 1026, y: 166 },
          { x: 1140, y: 166 },
        ],
      },
      nape: { anchor: { x: 1083, y: 251 }, centers: [{ x: 1083, y: 251 }] },
      'shoulder-blade': {
        anchor: { x: 1083, y: 349 },
        centers: [
          { x: 1007, y: 349 },
          { x: 1159, y: 349 },
        ],
      },
      spine: { anchor: { x: 1083, y: 491 }, centers: [{ x: 1083, y: 491 }] },
      hip: {
        anchor: { x: 1083, y: 677 },
        centers: [
          { x: 1032, y: 677 },
          { x: 1134, y: 677 },
        ],
      },
      tailbone: { anchor: { x: 1083, y: 732 }, centers: [{ x: 1083, y: 732 }] },
      wrist: {
        anchor: { x: 1064, y: 700 },
        centers: [
          { x: 806, y: 702 },
          { x: 1322, y: 698 },
        ],
      },
    },
    femaleFront: {
      forehead: { anchor: { x: 320, y: 116 }, centers: [{ x: 320, y: 116 }] },
      eye: {
        anchor: { x: 320, y: 151 },
        centers: [
          { x: 291, y: 151 },
          { x: 349, y: 151 },
        ],
      },
      nose: { anchor: { x: 320, y: 173 }, centers: [{ x: 320, y: 173 }] },
      cheek: {
        anchor: { x: 320, y: 186 },
        centers: [
          { x: 280, y: 186 },
          { x: 360, y: 186 },
        ],
      },
      ear: {
        anchor: { x: 320, y: 158 },
        centers: [
          { x: 248, y: 160 },
          { x: 392, y: 156 },
        ],
      },
      mouth: { anchor: { x: 320, y: 205 }, centers: [{ x: 320, y: 205 }] },
      jaw: {
        anchor: { x: 320, y: 222 },
        centers: [
          { x: 276, y: 222 },
          { x: 364, y: 222 },
        ],
      },
      chin: { anchor: { x: 320, y: 238 }, centers: [{ x: 320, y: 238 }] },
      throat: { anchor: { x: 320, y: 295 }, centers: [{ x: 320, y: 295 }] },
      collarbone: {
        anchor: { x: 320, y: 308 },
        centers: [
          { x: 249, y: 308 },
          { x: 391, y: 308 },
        ],
      },
      sternum: { anchor: { x: 320, y: 408 }, centers: [{ x: 320, y: 408 }] },
      belly: { anchor: { x: 320, y: 531 }, centers: [{ x: 320, y: 531 }] },
      navel: { anchor: { x: 320, y: 574 }, centers: [{ x: 320, y: 574 }] },
      hip: {
        anchor: { x: 320, y: 631 },
        centers: [
          { x: 285, y: 631 },
          { x: 355, y: 631 },
        ],
      },
      groin: { anchor: { x: 320, y: 732 }, centers: [{ x: 320, y: 732 }] },
      elbow: {
        anchor: { x: 300, y: 441 },
        centers: [
          { x: 173, y: 443 },
          { x: 427, y: 438 },
        ],
      },
      wrist: {
        anchor: { x: 307, y: 698 },
        centers: [
          { x: 47, y: 693 },
          { x: 566, y: 703 },
        ],
      },
    },
    femaleBack: {
      ear: {
        anchor: { x: 1147, y: 209 },
        centers: [
          { x: 1100, y: 212 },
          { x: 1194, y: 206 },
        ],
      },
      nape: { anchor: { x: 1142, y: 244 }, centers: [{ x: 1142, y: 244 }] },
      'shoulder-blade': {
        anchor: { x: 1142, y: 352 },
        centers: [
          { x: 1065, y: 352 },
          { x: 1219, y: 352 },
        ],
      },
      spine: { anchor: { x: 1142, y: 507 }, centers: [{ x: 1142, y: 507 }] },
      hip: {
        anchor: { x: 1142, y: 710 },
        centers: [
          { x: 1091, y: 710 },
          { x: 1193, y: 710 },
        ],
      },
      tailbone: { anchor: { x: 1136, y: 770 }, centers: [{ x: 1136, y: 770 }] },
      wrist: {
        anchor: { x: 1130, y: 672 },
        centers: [
          { x: 867, y: 685 },
          { x: 1393, y: 659 },
        ],
      },
    },
  };
