import { describe, it, expect } from 'vitest';
// @ts-expect-error — plain .mjs build script, no types; only the range tables are read.
import { TTF_DROP, WOFF2_KEEP } from '../scripts/build-fonts.mjs';

/**
 * Guards the coverage promise the font subsetting makes (issue #120).
 *
 * These assertions run against the RANGE TABLES, not against `fonts/*.ttf`.
 * `fonts/` is generated by `prebuild`, and CI runs `pnpm test` before
 * `pnpm build` — a test reading the generated files would either fail there or
 * need a skip guard that makes it never run at all.
 *
 * The failure this exists to catch: someone narrows the woff2 set to Basic
 * Latin to save a few more kilobytes. That is precisely what
 * `diagrammo_app_site/public/fonts/inter-latin.woff2` did, and it silently
 * stopped rendering six European languages.
 */

const covered = (cp: number, ranges: number[][]) =>
  ranges.some(([s, e]) => cp >= s && cp <= e);

/** Every letter here must survive in BOTH outputs. */
const LATIN_SCRIPT_EUROPE: Record<string, string> = {
  Polish: 'ŁłĄąĆćĘęŃńÓóŚśŹźŻż',
  Czech: 'ČčĎďŇňŘřŠšŤťŽžĚě',
  Slovak: 'ĹĺĽľŔŕŠšŤťŽž',
  Hungarian: 'ŐőŰű',
  Turkish: 'İıĞğŞş',
  Romanian: 'ĂăȘșȚțÂâÎî',
  Croatian: 'ĐđĆćČčŠšŽž',
  Baltic: 'ĀāĒēĪīŪūĶķĻļŅņŲų',
  German: 'ÄäÖöÜüß',
  French: 'ÀàÉéÈèÊêÇçŒœÙù',
  Spanish: 'ÁáÍíÑñÓóÚúÜü¡¿',
  Nordic: 'ÅåÆæØøÞþÐð',
  Vietnamese: 'ẠạẾếỆệỌọỸỹ',
};

/** Marks a diagram actually draws, so they must be in the font we control. */
const DIAGRAM_SYMBOLS = '→←↑↓✓✗★☆▲▼●■□½¼¾±×÷≤≥−—“”•€£¥™№';

describe('woff2 subset (browser)', () => {
  for (const [language, letters] of Object.entries(LATIN_SCRIPT_EUROPE)) {
    it(`keeps every letter ${language} needs`, () => {
      const missing = [...letters].filter(
        (c) => !covered(c.codePointAt(0)!, WOFF2_KEEP)
      );
      expect(missing.join('')).toBe('');
    });
  }

  it('keeps the symbols diagrams draw', () => {
    const missing = [...DIAGRAM_SYMBOLS].filter(
      (c) => !covered(c.codePointAt(0)!, WOFF2_KEEP)
    );
    expect(missing.join('')).toBe('');
  });

  it('keeps Latin Extended-A and -B whole — the blocks the accents live in', () => {
    for (const cp of [0x0100, 0x017f, 0x0180, 0x024f]) {
      expect(covered(cp, WOFF2_KEEP)).toBe(true);
    }
  });
});

describe('ttf subset (resvg — no system-font fallback)', () => {
  const dropped = (s: string) =>
    [...s].filter((c) => covered(c.codePointAt(0)!, TTF_DROP));

  for (const [language, letters] of Object.entries(LATIN_SCRIPT_EUROPE)) {
    it(`never drops ${language}`, () => {
      expect(dropped(letters).join('')).toBe('');
    });
  }

  it('never drops Greek or Cyrillic', () => {
    // The .woff2 may omit these — a browser falls back per glyph. resvg cannot,
    // so the .ttf must carry them.
    expect(dropped('ΑΒΓΔαβγδΆήώЀАБВГДабвгдЁёЇїЍ').join('')).toBe('');
  });

  it('never drops the symbols diagrams draw', () => {
    expect(dropped(DIAGRAM_SYMBOLS).join('')).toBe('');
  });

  it('drops only Private Use, polytonic Greek and IPA', () => {
    expect(TTF_DROP).toStrictEqual([
      [0xe000, 0xf8ff],
      [0x1f00, 0x1fff],
      [0x0250, 0x02af],
    ]);
  });
});
