// Typed contract for the committed map data assets in this directory.
// Generated bytes live in *.json; this file is hand-written and is the single
// source of truth for the shape the parser/resolver/renderer consume.
// Produced by scripts/build-map-data.mjs (run `pnpm build:map-data`).

/** A TopoJSON topology (world-coarse/world-detail keyed by ISO 3166-1 alpha-2;
 *  us-states keyed by ISO 3166-2). Geometry feature `id` is the ISO code;
 *  `properties.name` is the display string. Kept loose to avoid a topojson dep. */
export interface BoundaryTopology {
  type: 'Topology';
  objects: Record<string, { type: string; geometries: BoundaryGeometry[] }>;
  arcs: number[][][];
  transform?: { scale: [number, number]; translate: [number, number] };
  bbox?: number[];
}

export interface BoundaryGeometry {
  type: string;
  /** ISO code: alpha-2 (countries) or 3166-2 `US-XX` (states). */
  id: string;
  properties: { name: string };
  arcs?: unknown;
}

/**
 * A gazetteer city entry: `[lat, lon, iso, pop, name, sub?]`.
 * - `lat`/`lon` — rounded to 3 decimals.
 * - `iso` — ISO 3166-1 alpha-2 country code.
 * - `pop` — population.
 * - `name` — canonical display name (case/accents preserved).
 * - `sub` — ISO 3166-2 subdivision (US cities only in v1, e.g. `US-OR`); absent otherwise.
 */
export type GazetteerEntry = [
  lat: number,
  lon: number,
  iso: string,
  pop: number,
  name: string,
  sub?: string,
];

export interface Gazetteer {
  /** Every city, stored once. `byName`/`alt` reference cities by array index
   *  (normalized — no tuple duplication; geonameid is a build-time-only linker). */
  cities: GazetteerEntry[];
  /** Folded (NFD, diacritic-stripped, lowercased) name → indices into `cities`.
   *  Always an array; length > 1 for same-named cities (Portland US-OR / US-ME). */
  byName: Record<string, number[]>;
  /** Folded alias → index into `cities`. Never collides with a `byName` key. */
  alt: Record<string, number>;
}
