// Typed contract for the committed map data assets in this directory.
// Generated bytes live in *.json; this file is hand-written and is the single
// source of truth for the shape the parser/resolver/renderer consume.
// Produced by scripts/build-map-data.mjs (run `pnpm build:map-data`).

/** A TopoJSON topology (world-coarse/world-detail keyed by ISO 3166-1 alpha-2;
 *  us-states keyed by ISO 3166-2). Geometry feature `id` is the ISO code;
 *  `properties.name` is the display string. Kept loose to avoid a topojson dep. */
export interface BoundaryTopology {
  type: 'Topology';
  objects: Record<string, { type: string; geometries: BoundaryGeometry[] }>;
  arcs: number[][][];
  transform?: { scale: [number, number]; translate: [number, number] };
  bbox?: number[];
}

export interface BoundaryGeometry {
  type: string;
  /** ISO code: alpha-2 (countries) or 3166-2 `US-XX` (states). */
  id: string;
  properties: { name: string };
  arcs?: unknown;
}

/**
 * A gazetteer city entry: `[lat, lon, iso, pop, name, sub?]`.
 * - `lat`/`lon` — rounded to 3 decimals.
 * - `iso` — ISO 3166-1 alpha-2 country code.
 * - `pop` — population.
 * - `name` — canonical display name (case/accents preserved).
 * - `sub` — ISO 3166-2 subdivision (US cities only in v1, e.g. `US-OR`); absent otherwise.
 */
export type GazetteerEntry = [
  lat: number,
  lon: number,
  iso: string,
  pop: number,
  name: string,
  sub?: string,
];

export interface Gazetteer {
  /** Every city, stored once. `byName`/`alt` reference cities by array index
   *  (normalized — no tuple duplication; geonameid is a build-time-only linker). */
  cities: GazetteerEntry[];
  /** Folded (NFD, diacritic-stripped, lowercased) name → indices into `cities`.
   *  Always an array; length > 1 for same-named cities (Portland US-OR / US-ME). */
  byName: Record<string, number[]>;
  /** Folded alias → index into `cities`. Never collides with a `byName` key. */
  alt: Record<string, number>;
  /** BL-122 clock-on-map: distinct IANA zone ids (sorted), referenced by `tz`. */
  zones?: string[];
  /** BL-122: IANA zone per city, parallel to `cities` — `tz[i]` indexes `zones`
   *  (−1 when a city had no GeoNames match). Lets `poi Denver clock` derive its
   *  local time without the author restating the zone. */
  tz?: number[];
}

/**
 * IATA-coded airport index (a SEPARATE optional asset — `airports.json`; ADR-1).
 * Lets memorized airport codes resolve to coordinates through the resolver's
 * existing fold→lookup path (`poi JFK`, `route JFK -> LAX`) — no parser change.
 *
 * - `airports` — `GazetteerEntry` tuples `[lat, lon, iso, 0, name]`. `pop` is
 *   always 0 (OurAirports has no enplanement column); `name` is the full airport
 *   name, used for COMPLETION DISPLAY only — airports resolve by IATA code, never
 *   by name. Coords are rounded to 2 decimals (~1km; sub-pixel at map scale).
 * - `airportIata` — folded 3-letter IATA code → index into `airports`. Consulted
 *   LAST in resolution (after city `byName` + `alt`), so a real city always wins
 *   a shared token (ADR-2). Airports never enter `cities[]`, so the city-scatter
 *   and reverse-geocode layers never see them.
 */
export interface AirportData {
  readonly airports: GazetteerEntry[];
  readonly airportIata: Record<string, number>;
}

/** Water-feature class (Natural Earth `featurecla`, rivers/reefs excluded). */
export type WaterKind =
  | 'ocean'
  | 'sea'
  | 'gulf'
  | 'bay'
  | 'strait'
  | 'channel'
  | 'sound';

/**
 * A water-body label entry: `[lat, lon, name, tier, kind, alt?]`.
 * - `lat`/`lon` — label anchor (Natural Earth inner point), rounded to 3 decimals.
 * - `name` — full display name (no abbreviation exists for water bodies).
 * - `tier` — Natural Earth `scalerank` (0 = most prominent → orientation priority).
 * - `kind` — feature class (drives styling/priority bucketing).
 * - `alt` — optional extra anchor points `[lat, lon][]`; the layout picks the
 *   one nearest the viewport center (Decision 5 multi-anchor seam). Absent today.
 */
export type WaterBodyEntry = [
  lat: number,
  lon: number,
  name: string,
  tier: number,
  kind: WaterKind,
  alt?: ReadonlyArray<readonly [number, number]>,
];

export interface WaterBodies {
  /** Deterministically ordered (tier, then name). Generated from Natural Earth
   *  marine polys by scripts/build-map-data.mjs into `water-bodies.json`. */
  readonly entries: readonly WaterBodyEntry[];
}

/** A fill-able region (country or US state) — the display name + its ISO id +
 *  layer. Powers region-name autocomplete (completion-only; the renderer derives
 *  names from the topology directly). Extracted from the topologies by
 *  scripts/build-map-data.mjs into `region-names.json`. */
export interface RegionName {
  /** Display name (original casing), e.g. `California` / `Germany`. */
  readonly name: string;
  /** ISO 3166-1 alpha-2 (country) or 3166-2 `US-XX` (state). */
  readonly iso: string;
  readonly layer: 'country' | 'us-state';
}

export interface RegionNames {
  /** Deterministically ordered (layer, then name). */
  readonly regions: readonly RegionName[];
}
