// ============================================================
// Sketch diagram — Types
// ============================================================
//
// GUI-first constrained canvas (spec §31): uniformly-sized shapes placed on a
// half-slot lattice, arrows between them, meaning through tags. The markup is
// generated by the app's canvas editor; the parser stays lenient toward
// hand-authored files (optional `at:`, overlap auto-resolve at layout).

import type { DgmoError } from '../diagnostics';
import type { TagGroup } from '../utils/tag-groups';

/** Closed shape lexicon — rectangle is the default and never written. */
export const SKETCH_SHAPE_KINDS = [
  'rectangle',
  'database',
  'queue',
  'person',
  'document',
  'note',
] as const;

export type SketchShapeKind = (typeof SKETCH_SHAPE_KINDS)[number];

/** Half-slot lattice position (spec §31.3). Box children are box-relative. */
export interface SketchAt {
  readonly c: number;
  readonly r: number;
}

export interface SketchNode {
  /** Synthetic stable id (parse-order); use alias/label indexes to resolve. */
  readonly id: string;
  readonly label: string;
  readonly alias?: string;
  readonly shape: SketchShapeKind;
  /** null → flow auto-place at layout */
  readonly at: SketchAt | null;
  /** tag metadata only (shape/at/alias are lifted out) */
  readonly metadata: Record<string, string>;
  /** owning box label (undefined = root) */
  readonly boxLabel?: string;
  readonly lineNumber: number;
}

export type SketchEdgeHeads = 'one' | 'both' | 'none';

export interface SketchEdge {
  readonly sourceId: string;
  readonly targetId: string;
  readonly label?: string;
  readonly heads: SketchEdgeHeads;
  /** dashed = "secondary", NOT async (spec §31.4 divergence note) */
  readonly dashed: boolean;
  readonly metadata: Record<string, string>;
  readonly lineNumber: number;
}

export interface SketchBox {
  /** `[<normalized label>]` — the infra group-id scheme */
  readonly id: string;
  readonly label: string;
  readonly alias?: string;
  readonly at: SketchAt | null;
  readonly metadata: Record<string, string>;
  readonly collapsed: boolean;
  /** child node ids, declaration order */
  readonly children: readonly string[];
  readonly lineNumber: number;
}

export interface SketchOptions {
  readonly noLegend: boolean;
  readonly solidFill: boolean;
}

export interface ParsedSketch {
  readonly type: 'sketch';
  readonly title: string | null;
  readonly titleLineNumber: number | null;
  readonly nodes: readonly SketchNode[];
  readonly edges: readonly SketchEdge[];
  readonly boxes: readonly SketchBox[];
  readonly tagGroups: readonly TagGroup[];
  readonly options: SketchOptions;
  readonly diagnostics: readonly DgmoError[];
  readonly error: string | null;
}

export function isSketchShapeKind(value: string): value is SketchShapeKind {
  return (SKETCH_SHAPE_KINDS as readonly string[]).includes(value);
}
