// ============================================================
// Sketch diagram — Types
// ============================================================
//
// GUI-first constrained canvas (spec §31): uniformly-sized shapes placed on a
// half-slot lattice, arrows between them, meaning through tags. The markup is
// generated by the app's canvas editor; the parser stays lenient toward
// hand-authored files (optional `at:`, overlap auto-resolve at layout).

import type { DgmoError } from '../diagnostics';
import type { TagGroup } from '../utils/tag-groups';

/** Closed shape lexicon — rectangle is the default and never written. */
export const SKETCH_SHAPE_KINDS = [
  'rectangle',
  'database',
  'queue',
  'person',
  'document',
  'note',
] as const;

export type SketchShapeKind = (typeof SKETCH_SHAPE_KINDS)[number];

/** Half-slot lattice position (spec §31.3). Box children are box-relative. */
export interface SketchAt {
  readonly c: number;
  readonly r: number;
}

export interface SketchNode {
  /** Synthetic stable id (parse-order); use alias/label indexes to resolve. */
  readonly id: string;
  readonly label: string;
  readonly alias?: string;
  readonly shape: SketchShapeKind;
  /** null → flow auto-place at layout */
  readonly at: SketchAt | null;
  /** tag metadata only (shape/at/alias are lifted out) */
  readonly metadata: Record<string, string>;
  /** Free-text markdown description (indented `>` lines under the shape).
   *  Newline-joined; a small markdown subset renders in the card body. */
  readonly description?: string;
  /** owning box label (undefined = root) */
  readonly boxLabel?: string;
  readonly lineNumber: number;
}

export type SketchEdgeHeads = 'one' | 'both' | 'none';

export interface SketchEdge {
  readonly sourceId: string;
  readonly targetId: string;
  readonly label?: string;
  readonly heads: SketchEdgeHeads;
  /** dashed = "secondary", NOT async (spec §31.4 divergence note) */
  readonly dashed: boolean;
  readonly metadata: Record<string, string>;
  readonly lineNumber: number;
}

export interface SketchBox {
  /** `[<normalized label>]` — the infra group-id scheme */
  readonly id: string;
  readonly label: string;
  readonly alias?: string;
  readonly at: SketchAt | null;
  readonly metadata: Record<string, string>;
  readonly collapsed: boolean;
  /** child node ids, declaration order */
  readonly children: readonly string[];
  /**
   * Child BOX ids, declaration order (decision #58 — sketch nests to depth 2,
   * matching boxes-and-lines §14). Empty on an inner box: depth 2 is the bound.
   */
  readonly childBoxes: readonly string[];
  /**
   * The box this box sits inside, or null at the top level. Membership lives on
   * the CHILD, the same shape `boxes-and-lines` uses (`parentGroup`) and the one
   * the sketch rebuild's canvas model arrived at independently — a tree cannot
   * express double membership, so this cannot either.
   */
  readonly parentBoxId: string | null;
  readonly lineNumber: number;
}

export interface SketchOptions {
  readonly noLegend: boolean;
  /** §1.9 `legend-inline` — title left, legend flushed right on one row. */
  readonly legendInline?: boolean;
  /** §1.9 fill family; undefined ⇒ canonical 25% tint. */
  readonly fillMode: 'solid' | 'outline' | undefined;
  /** `no-descriptions` directive (mindmap `hd` standard): hide the card
   *  metadata rows so each card is just its name. */
  readonly noDescriptions: boolean;
  /**
   * §1.9 `no-title` — keep the title in the source, do not draw it.
   *
   * ⚠️ NOT the same state as clearing the title on the canvas, which deletes
   * the text and emits a bare `sketch`. This one keeps `sketch Ship` in the
   * file and only suppresses the drawing, which is why it is not a second
   * spelling of the rename gesture (#607).
   */
  readonly noTitle: boolean;
}

export interface ParsedSketch {
  readonly type: 'sketch';
  readonly title: string | null;
  readonly titleLineNumber: number | null;
  readonly nodes: readonly SketchNode[];
  readonly edges: readonly SketchEdge[];
  readonly boxes: readonly SketchBox[];
  readonly tagGroups: readonly TagGroup[];
  readonly options: SketchOptions;
  readonly diagnostics: readonly DgmoError[];
  readonly error: string | null;
}

export function isSketchShapeKind(value: string): value is SketchShapeKind {
  return (SKETCH_SHAPE_KINDS as readonly string[]).includes(value);
}
