#!/usr/bin/env tsx
/**
 * One-shot audit for the `option solid-fill` spike.
 *
 * For each (palette × theme × intent) combination, computes the WCAG contrast
 * ratio between the saturated intent fill and whichever text token
 * `contrastText()` would resolve to (`textOnFillLight` / `textOnFillDark`).
 * Flags any row below 3:1 (WCAG AA Large) with `⚠`.
 *
 * Output is a markdown table (stdout). Capture with:
 *   tsx scripts/audit-solid-fill-contrast.ts > /tmp/solid-fill-audit.md
 *
 * NOT a permanent vitest assertion — see TD-11 in
 * `_bmad-output/implementation-artifacts/tech-spec-option-solid-fill-spike.md`.
 */

import {
  atlasPalette,
  blueprintPalette,
  catppuccinPalette,
  nordPalette,
  slatePalette,
  tidewaterPalette,
  tokyoNightPalette,
} from '../src/palettes';
import type { PaletteColors, PaletteConfig } from '../src/palettes/types';
import { contrastText, relativeLuminance } from '../src/palettes/color-utils';

const PALETTES: PaletteConfig[] = [
  atlasPalette,
  blueprintPalette,
  catppuccinPalette,
  nordPalette,
  slatePalette,
  tidewaterPalette,
  tokyoNightPalette,
];

const INTENTS: (keyof PaletteColors['colors'])[] = [
  'red',
  'orange',
  'yellow',
  'green',
  'blue',
  'purple',
  'teal',
  'cyan',
];

const WCAG_AA_LARGE = 3.0;

function contrastRatio(a: string, b: string): number {
  const la = relativeLuminance(a);
  const lb = relativeLuminance(b);
  const lighter = Math.max(la, lb);
  const darker = Math.min(la, lb);
  return (lighter + 0.05) / (darker + 0.05);
}

interface Row {
  palette: string;
  theme: 'light' | 'dark';
  intent: string;
  intentHex: string;
  textHex: string;
  ratio: number;
  warn: boolean;
}

function buildRows(): Row[] {
  const rows: Row[] = [];
  for (const palette of PALETTES) {
    for (const theme of ['light', 'dark'] as const) {
      const colors = palette[theme];
      for (const intent of INTENTS) {
        const intentHex = colors.colors[intent];
        const textHex = contrastText(
          intentHex,
          colors.textOnFillLight,
          colors.textOnFillDark
        );
        const ratio = contrastRatio(intentHex, textHex);
        rows.push({
          palette: palette.name,
          theme,
          intent,
          intentHex,
          textHex,
          ratio,
          warn: ratio < WCAG_AA_LARGE,
        });
      }
    }
  }
  return rows;
}

function emit(rows: Row[]): void {
  console.log('# Solid-Fill Contrast Audit');
  console.log('');
  console.log(
    `Generated by \`scripts/audit-solid-fill-contrast.ts\`. ${rows.length} rows ` +
      `(${PALETTES.length} palettes × 2 themes × ${INTENTS.length} intents).`
  );
  console.log('');
  console.log(
    'Each row contrasts the **raw intent color** (what `solid-fill` produces) ' +
      'against the text token `contrastText()` selects. ' +
      `Rows below ${WCAG_AA_LARGE.toFixed(1)}:1 (WCAG AA Large) are flagged with \`⚠\`.`
  );
  console.log('');

  let lastPalette = '';
  for (const row of rows) {
    if (row.palette !== lastPalette) {
      if (lastPalette !== '') console.log('');
      console.log(`## ${row.palette}`);
      console.log('');
      console.log('| Theme | Intent | Intent hex | Text hex | Ratio | |');
      console.log('|-------|--------|------------|----------|-------|--|');
      lastPalette = row.palette;
    }
    const flag = row.warn ? '⚠' : ' ';
    console.log(
      `| ${row.theme} | ${row.intent} | \`${row.intentHex}\` | \`${row.textHex}\` | ${row.ratio.toFixed(2)} | ${flag} |`
    );
  }

  const failing = rows.filter((r) => r.warn);
  console.log('');
  console.log('## Summary');
  console.log('');
  console.log(`- Total rows: ${rows.length}`);
  console.log(`- Failing (<${WCAG_AA_LARGE.toFixed(1)}:1): ${failing.length}`);
  if (failing.length > 0) {
    console.log('');
    console.log('### Failing combinations');
    console.log('');
    for (const r of failing) {
      console.log(
        `- **${r.palette}** ${r.theme} ${r.intent}: ${r.ratio.toFixed(2)}:1 (\`${r.intentHex}\` on \`${r.textHex}\`)`
      );
    }
  }
}

emit(buildRows());
