// ============================================================
// gen-ai-core.mjs — emit the single-sourced DGMO AI core into every embedded
// surface (Task 4, STRUCTURAL-LITE scope).
//
// The Tier-0 universal core lives ONCE, in language-reference.md's
// `<!-- AI-CORE:ANTIPATTERNS -->` + `<!-- AI-CORE:TYPE-INDEX -->` blocks. This
// script extracts them and writes them — with a generated-file banner — into a
// `<!-- DGMO-AI-CORE:START --> … <!-- DGMO-AI-CORE:END -->` region in each
// surface. Only the depth pointer differs per surface (MCP tools vs hosted
// URL). Editing a generated region by hand is pointless: re-running this
// overwrites it. Drift of the high-value anti-patterns is structurally
// impossible.
//
// Every emitted ```dgmo fence is parsed via the SHARED fence-validate.mjs (the
// same path the CI gate uses, ADR-8/AC16) and the script exits non-zero on any
// error/warning or on an incomplete core (AC12).
//
// NOTE (LITE): the per-surface curated quick-reference examples are NOT yet
// generated — they remain hand-authored but gate-covered. Single-sourcing the
// top-N per-type examples is the deferred Task-3 curation.
//
// Run: node scripts/gen-ai-core.mjs        (writes; exits non-zero on a problem)
// ============================================================

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { chartTypes } from '@diagrammo/dgmo/advanced';
import { extractAiCore } from './lib/ref-anchors.mjs';
import { extractDgmoFences, validateDgmoSource, formatDiagnostic } from './lib/fence-validate.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..'); // dgmo/
const REF = 'docs/language-reference.md';
const START = '<!-- DGMO-AI-CORE:START -->';
const END = '<!-- DGMO-AI-CORE:END -->';

const BANNER =
  '<!-- GENERATED by dgmo/scripts/gen-ai-core.mjs from docs/language-reference.md — DO NOT EDIT between the DGMO-AI-CORE markers; run `node scripts/gen-ai-core.mjs` (or sync-language-ref.sh) to regenerate. -->';

// Surfaces that carry the core, with their depth pointer (Tier 1/2 fetch path).
const SURFACES = [
  { path: '.cursorrules', pointer: 'url' },
  { path: '.windsurfrules', pointer: 'url' },
  { path: '.github/copilot-instructions.md', pointer: 'url' },
  { path: 'SKILL.md', pointer: 'mcp' },
  { path: 'docs/ai-integration.md', pointer: 'mcp' },
];

const POINTERS = {
  mcp: '**Fetch more:** call `get_language_reference(type)` for a type\'s full syntax and `get_examples(type)` for starter templates. `suggest_chart_type` returns the chosen type\'s reference automatically.',
  url: '**Fetch more:** the full per-type reference is at https://diagrammo.app/docs — fetch a type\'s section when the index + anti-patterns above aren\'t enough.',
};

function fail(msg) {
  console.error(`gen-ai-core: ${msg}`);
  process.exit(1);
}

// --- extract + validate the core -------------------------------------------
const refMd = readFileSync(join(repo, REF), 'utf8');
const antipatterns = extractAiCore(refMd, 'ANTIPATTERNS');
const typeIndex = extractAiCore(refMd, 'TYPE-INDEX');

if (!antipatterns) fail('AI-CORE:ANTIPATTERNS block missing or empty in ' + REF);
if (!typeIndex) fail('AI-CORE:TYPE-INDEX block missing or empty in ' + REF);

// Completeness (AC12): every chart-type id must appear in the index.
const missing = chartTypes.filter((c) => !new RegExp(`\`${c.id}\``).test(typeIndex)).map((c) => c.id);
if (missing.length) fail(`TYPE-INDEX is missing ${missing.length} id(s): ${missing.join(', ')}`);

// Validate every fence in the core BEFORE emitting (fail fast for authors).
for (const f of extractDgmoFences(antipatterns, REF)) {
  if (f.counterExample) continue;
  const { errors, warnings } = validateDgmoSource(f.source);
  const bad = [...errors, ...warnings];
  if (bad.length) fail(`core example at ${REF}:${f.line} is not clean:\n  ${bad.map(formatDiagnostic).join('\n  ')}`);
}

function buildCore(pointer) {
  return [
    BANNER,
    START,
    '## DGMO AI Core',
    '',
    '_Generated from `language-reference.md` — the anti-patterns and 45-type index below are identical across every DGMO AI surface._',
    '',
    antipatterns,
    '',
    typeIndex,
    '',
    POINTERS[pointer],
    END,
  ].join('\n');
}

// --- emit into each surface --------------------------------------------------
let wrote = 0;
const cursorWindsurf = [];
for (const { path, pointer } of SURFACES) {
  const file = join(repo, path);
  let content;
  try {
    content = readFileSync(file, 'utf8');
  } catch {
    fail(`surface not found: ${path} (expected the DGMO-AI-CORE markers to be present)`);
  }
  const block = buildCore(pointer);
  const re = new RegExp(`${BANNER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\n${START}[\\s\\S]*?${END}`);
  const reBare = new RegExp(`${START}[\\s\\S]*?${END}`);
  let next;
  if (re.test(content)) {
    next = content.replace(re, block);
  } else if (reBare.test(content)) {
    next = content.replace(reBare, block);
  } else {
    fail(`${path} has no ${START} … ${END} markers — add them where the core should land, then re-run.`);
  }
  if (next !== content) {
    writeFileSync(file, next);
    wrote++;
  }
  if (path === '.cursorrules' || path === '.windsurfrules') cursorWindsurf.push(next);
  console.log(`gen-ai-core: ${path} (${next === content ? 'unchanged' : 'updated'})`);
}

// .cursorrules and .windsurfrules must stay byte-identical (AC4).
if (cursorWindsurf.length === 2 && cursorWindsurf[0] !== cursorWindsurf[1]) {
  fail('.cursorrules and .windsurfrules diverged — they must be byte-identical.');
}

console.log(`gen-ai-core: done (${wrote} file(s) changed, core = ${chartTypes.length} types).`);
