// Regenerates the suggest_chart_type audit report from the committed corpus.
// Run: `pnpm suggest-audit` (reads dist — rebuild if the scorer changed).
// The hit-rate this prints is the baseline the regression test guards.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { suggestChartTypes } = require('../dist/advanced.cjs');
const corpus = JSON.parse(readFileSync('./tests/fixtures/suggest-corpus.json', 'utf8'));

/** Verdict for one labeled prompt against the live scorer. */
export function gradeEntry(entry) {
  const r = suggestChartTypes(entry.prompt);
  const ids = r.ranked.map((x) => x.type.id);
  const v = r.fellBack
    ? 'miss'
    : ids[0] && entry.expected.includes(ids[0])
      ? 'top1'
      : ids.slice(0, 3).some((id) => entry.expected.includes(id))
        ? 'top3'
        : 'miss';
  const top3 = r.ranked
    .slice(0, 3)
    .map((x) => `${x.type.id} (${x.score}${x.matched.length ? ' ←' + x.matched.join(',') : ''})`)
    .join(' · ');
  return { entry, v, confidence: r.confidence, fellBack: r.fellBack, top3: top3 || '— none —' };
}

export function grade(rows) {
  const graded = rows.map(gradeEntry);
  const top1 = graded.filter((g) => g.v === 'top1').length;
  const top3 = graded.filter((g) => g.v === 'top1' || g.v === 'top3').length;
  return { graded, top1, top3, total: rows.length };
}

function main() {
  const { graded, top1, top3, total } = grade(corpus);
  const pct = (n) => `${n}/${total} (${Math.round((100 * n) / total)}%)`;
  const misses = graded.filter((g) => g.v === 'miss');

  const row = (g) =>
    `| ${g.entry.prompt} | ${g.entry.expected.join(' / ')} | ` +
    `${g.v === 'top1' ? '✅ top-1' : g.v === 'top3' ? '🟡 top-3' : '❌ miss'} | ` +
    `${g.confidence}${g.fellBack ? ' · fb' : ''} | ${g.top3} |`;

  const md = `# suggest_chart_type — audit report

_Auto-generated by \`pnpm suggest-audit\` from \`tests/fixtures/suggest-corpus.json\` (${total} labeled prompts). Do not hand-edit — edit the corpus and regenerate. Iterate interactively with \`pnpm cockpit\`._

## Hit-rate (current scorer)

- **top-1 confident-correct: ${pct(top1)}**
- **expected-in-top-3: ${pct(top3)}**

A "miss" means the scorer fell back (no real trigger fired) or ranked the wrong type first. The contiguous-phrase matcher only fires on near-verbatim trigger phrases, so natural paraphrases miss — that gap is the point of this report.

## Worst misses (${misses.length})

| prompt | expected | verdict | conf | top 3 (score ←matched) |
|--------|----------|:------:|------|------------------------|
${misses.map(row).join('\n')}

## Full corpus

| prompt | expected | verdict | conf | top 3 (score ←matched) |
|--------|----------|:------:|------|------------------------|
${graded.map(row).join('\n')}
`;

  const out = './tools/suggest-cockpit/audit.md';
  writeFileSync(out, md);
  console.log(`wrote ${out}`);
  console.log(`baseline: top-1 ${top1}/${total} · top-3 ${top3}/${total}`);
}

// Run only when invoked directly (the test imports grade()).
if (import.meta.url === `file://${process.argv[1]}`) main();
