/**
 * Which characters the bundled Inter cannot draw.
 *
 * Inter covers Latin, Greek and Cyrillic. It has no CJK, Devanagari, Tamil,
 * Arabic, Hebrew or Thai — and never did, upstream included. In a browser that
 * is harmless: `FONT_FAMILY` ends in `system-ui, …, sans-serif` and the browser
 * walks that chain per character, so a Japanese reader sees Japanese.
 *
 * 🔴 When rasterising it is not harmless. resvg resolves the whole family chain
 * against the fonts it was given, so text in a script the bundled font lacks
 * falls back to whatever system fonts resvg loaded — and if it loaded none, it
 * draws NOTHING. Not a .notdef box: nothing, silently, exit code 0. Measured
 * 2026-08-07 on `@diagrammo/dgmo-cli` 0.62.3 — a bar chart labelled 日本語
 * rasterised to pixels identical to one labelled with a Private Use codepoint
 * that exists in no font at all.
 *
 * That is why `loadSystemFonts` is now always on at both rasterising call sites.
 * This module covers what that fix cannot: a machine with no font for the script
 * — a bare CI container, most Docker images — still draws nothing, and the
 * output is silently wrong rather than loudly broken. So a diagram carrying
 * characters outside the bundled coverage is a PORTABILITY warning: it renders
 * here because this machine happens to have a font, and may not render there.
 *
 * Coverage is read from `fonts/coverage.json`, generated by
 * `scripts/build-fonts.mjs` from the real subset output — never hand-written,
 * so it cannot drift from the bytes actually shipped.
 */

/** A closed codepoint range, `[start, end]` inclusive. */
export type CodepointRange = readonly [number, number];

/** What `fonts/coverage.json` holds. */
export interface FontCoverage {
  /** Ranges the built TTF actually contains, ascending and non-overlapping. */
  readonly ranges: readonly CodepointRange[];
}

/** One run of characters the bundled font cannot draw. */
export interface UncoveredRun {
  /** The characters themselves, deduplicated, in first-seen order. */
  readonly characters: string;
  /** A human-readable guess at the script, for the message. */
  readonly script: string;
  /** How many distinct codepoints in this run. */
  readonly count: number;
}

/**
 * Script names for the blocks Inter does not cover. Deliberately coarse — this
 * names the writing system in a warning, it does not classify text. Anything
 * unmatched is reported as "other", which is honest rather than wrong.
 */
const SCRIPT_BLOCKS: readonly (readonly [number, number, string])[] = [
  [0x0590, 0x05ff, 'Hebrew'],
  [0x0600, 0x06ff, 'Arabic'],
  [0x0700, 0x074f, 'Syriac'],
  [0x0900, 0x097f, 'Devanagari'],
  [0x0980, 0x09ff, 'Bengali'],
  [0x0a00, 0x0a7f, 'Gurmukhi'],
  [0x0a80, 0x0aff, 'Gujarati'],
  [0x0b00, 0x0b7f, 'Odia'],
  [0x0b80, 0x0bff, 'Tamil'],
  [0x0c00, 0x0c7f, 'Telugu'],
  [0x0c80, 0x0cff, 'Kannada'],
  [0x0d00, 0x0d7f, 'Malayalam'],
  [0x0e00, 0x0e7f, 'Thai'],
  [0x1000, 0x109f, 'Burmese'],
  [0x1100, 0x11ff, 'Korean'],
  [0x3040, 0x309f, 'Japanese'],
  [0x30a0, 0x30ff, 'Japanese'],
  [0x3400, 0x4dbf, 'Chinese'],
  [0x4e00, 0x9fff, 'Chinese'],
  [0xac00, 0xd7af, 'Korean'],
  [0xf900, 0xfaff, 'Chinese'],
  [0x1f300, 0x1faff, 'emoji'],
];

function scriptOf(cp: number): string {
  for (const [start, end, name] of SCRIPT_BLOCKS) {
    if (cp >= start && cp <= end) return name;
  }
  return 'other';
}

function covered(cp: number, ranges: readonly CodepointRange[]): boolean {
  // Ranges are ascending, so a binary search would be faster — but there are
  // ~30 of them and this runs once per render, so clarity wins.
  return ranges.some(([start, end]) => cp >= start && cp <= end);
}

/**
 * Pull the drawable text out of a rendered SVG.
 *
 * Reads `<text>` and `<tspan>` content rather than the diagram source, because
 * the source also holds directives, colour names and chart-type keywords that
 * are never drawn — warning about a character in a line nobody sees would be
 * noise. Entities are decoded, since `&amp;` reaches the font as `&`.
 */
export function textFromSvg(svg: string): string {
  const parts: string[] = [];
  const element = /<(?:text|tspan)\b[^>]*>([\s\S]*?)<\/(?:text|tspan)>/g;
  let match: RegExpExecArray | null;
  while ((match = element.exec(svg)) !== null) {
    parts.push((match[1] ?? '').replace(/<[^>]*>/g, ''));
  }
  return parts
    .join('')
    .replace(/&#x([0-9a-f]+);/gi, (_, hex) =>
      String.fromCodePoint(parseInt(hex, 16))
    )
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
}

/**
 * Group the characters of `text` that the bundled font cannot draw, by script.
 *
 * Control characters and whitespace are ignored — they are never drawn and a
 * newline is not a coverage gap.
 */
export function uncoveredCharacters(
  text: string,
  coverage: FontCoverage
): readonly UncoveredRun[] {
  const byScript = new Map<string, string[]>();
  const seen = new Set<number>();

  for (const char of text) {
    const cp = char.codePointAt(0);
    if (cp === undefined || seen.has(cp)) continue;
    seen.add(cp);
    if (cp < 0x20 || cp === 0x7f) continue;
    if (/\s/.test(char)) continue;
    if (covered(cp, coverage.ranges)) continue;

    const script = scriptOf(cp);
    const bucket = byScript.get(script);
    if (bucket) bucket.push(char);
    else byScript.set(script, [char]);
  }

  return [...byScript.entries()].map(([script, chars]) => ({
    script,
    characters: chars.join(''),
    count: chars.length,
  }));
}

/**
 * The warning a rasterising caller should print, or `undefined` when every
 * character is covered.
 *
 * Phrased as portability rather than failure, because with system fonts loaded
 * it usually HAS rendered on this machine — the risk is the next machine. It
 * never says "will not render", which would be wrong here and ignored there.
 */
export function fontPortabilityWarning(
  runs: readonly UncoveredRun[]
): string | undefined {
  if (runs.length === 0) return undefined;

  const described = runs
    .map((run) => {
      const sample = [...run.characters].slice(0, 6).join('');
      const more = run.count > 6 ? ` +${run.count - 6} more` : '';
      return `${run.script} (${sample}${more})`;
    })
    .join(', ');

  return (
    `This diagram uses characters the bundled Inter font does not contain: ${described}. ` +
    `They were drawn with a font installed on this machine, so the image is correct here — ` +
    `but a machine without a font for those characters draws nothing at all, with no error. ` +
    `Install a font covering them wherever this runs, or check the output there.`
  );
}
